
import conexion.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mauri
 */
public class Login extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    int xmouse, ymouse;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        textusuarios = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        textcontraseña = new javax.swing.JPasswordField();
        Botonentrar = new javax.swing.JPanel();
        entar = new javax.swing.JLabel();
        salirboton = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        moivimiento = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titulo.setText("LOGIN");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 230, 90));

        contra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        contra.setText("Contraseña");
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 150, 40));

        user.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        user.setText("Usuario");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 150, 40));

        textusuarios.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        textusuarios.setForeground(new java.awt.Color(204, 204, 204));
        textusuarios.setText("ingrese su usuario");
        textusuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textusuariosMousePressed(evt);
            }
        });
        jPanel1.add(textusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 320, 30));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foto.jpg"))); // NOI18N
        foto.setText("jLabel5");
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        textcontraseña.setForeground(new java.awt.Color(204, 204, 204));
        textcontraseña.setText("**********");
        textcontraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textcontraseñaMousePressed(evt);
            }
        });
        jPanel1.add(textcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 320, 30));

        Botonentrar.setBackground(new java.awt.Color(0, 152, 219));

        entar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        entar.setForeground(new java.awt.Color(255, 255, 255));
        entar.setText("         ENTRAR ");
        entar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonentrarLayout = new javax.swing.GroupLayout(Botonentrar);
        Botonentrar.setLayout(BotonentrarLayout);
        BotonentrarLayout.setHorizontalGroup(
            BotonentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonentrarLayout.createSequentialGroup()
                .addComponent(entar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BotonentrarLayout.setVerticalGroup(
            BotonentrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(Botonentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, 40));

        salirboton.setBackground(new java.awt.Color(255, 255, 255));

        x.setBackground(new java.awt.Color(255, 255, 255));
        x.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        x.setText("  x");
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirbotonLayout = new javax.swing.GroupLayout(salirboton);
        salirboton.setLayout(salirbotonLayout);
        salirbotonLayout.setHorizontalGroup(
            salirbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirbotonLayout.createSequentialGroup()
                .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        salirbotonLayout.setVerticalGroup(
            salirbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(x, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(salirboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 50, 40));

        moivimiento.setBackground(new java.awt.Color(255, 255, 255));
        moivimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moivimientoMouseDragged(evt);
            }
        });
        moivimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moivimientoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout moivimientoLayout = new javax.swing.GroupLayout(moivimiento);
        moivimiento.setLayout(moivimientoLayout);
        moivimientoLayout.setHorizontalGroup(
            moivimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        moivimientoLayout.setVerticalGroup(
            moivimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(moivimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moivimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moivimientoMousePressed

        xmouse = evt.getX();
        ymouse = evt.getY();


    }//GEN-LAST:event_moivimientoMousePressed

    private void moivimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moivimientoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_moivimientoMouseDragged

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        salirboton.setBackground(Color.red);
        x.setForeground(Color.white);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        salirboton.setBackground(Color.white);
        x.setForeground(Color.black);
    }//GEN-LAST:event_xMouseExited

    private void entarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entarMouseEntered
        Botonentrar.setBackground(new Color(0, 165, 237));
    }//GEN-LAST:event_entarMouseEntered

    private void entarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entarMouseExited
        Botonentrar.setBackground(new Color(0, 152, 219));
    }//GEN-LAST:event_entarMouseExited

    private void textusuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textusuariosMousePressed
        if (textusuarios.getText().equals("ingrese su usuario")) {
            textusuarios.setText("");
            textusuarios.setForeground(Color.black);
        }

        if (String.valueOf(textcontraseña.getPassword()).isEmpty()) {
            textcontraseña.setText("**********");
            textcontraseña.setForeground(Color.gray);
        }

    }//GEN-LAST:event_textusuariosMousePressed

    private void textcontraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textcontraseñaMousePressed
        if (textusuarios.getText().isEmpty()) {
            textusuarios.setText("ingrese su usuario");
            textusuarios.setForeground(Color.gray);
        }

        if (String.valueOf(textcontraseña.getPassword()).equals("**********")) {
            textcontraseña.setText("");
            textcontraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_textcontraseñaMousePressed

    private void entarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entarMouseClicked
        String contra = String.valueOf(textcontraseña.getPassword());
        String rol = "";
        try {
            conexion.Declarar(textusuarios.getText(), contra);
            rol = conexion.ObtenerUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (rol.equals("administrador")) {
            this.dispose();

            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Sistema de Inventario");

                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(1000, 400);
                frame.setLocationRelativeTo(null);
                try {
                    frame.setContentPane(new Panel_Inventario());
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                frame.setVisible(true);
            });

        } else if (rol.equals("vendedor")) {
            this.dispose();

            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Sistema de ventas");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(1000, 400);
                frame.setLocationRelativeTo(null);
                try {
                    frame.setContentPane(new Panel_Ventas());
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                frame.setVisible(true);
            });
        }

    }//GEN-LAST:event_entarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botonentrar;
    private javax.swing.JLabel contra;
    private javax.swing.JLabel entar;
    private javax.swing.JLabel foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel moivimiento;
    private javax.swing.JPanel salirboton;
    private javax.swing.JPasswordField textcontraseña;
    private javax.swing.JTextField textusuarios;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel user;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
